### ISSUE TITLE
Integrate last AutoLayout release

### ISSUE THREAD

**Issue by aloisdeniel** [dnb-asa/figma#17]
A new release has been deployed which adds support for new auto layout properties.

It breaks the current parsing because of new enum values (like `INHERIT` for `layoutAlign`).

**Comment by aloisdeniel** [comment]
Created the #18 PR.

**Comment by aloisdeniel** [comment]
Thanks for the merge ! 👍 

I'm suspecting that the API isn't complete yet though (for example, all item should have `paddingLeft` regarding the last functionalities. So, new updates will probably needed very soon. But at list it runs well now. :)

**Comment by arnemolland** [comment]
Yeah, I expect the API to change soon as well. I'm also thinking the node converter could be built to not break each time Figma adds new node types, but I'll make a separate issue for that.
