### ISSUE TITLE
Canvas parsed as a Node

### ISSUE THREAD

**Issue by aloisdeniel** [dnb-asa/figma#4]
Thanks for implementing all of this! It is a time saver!

When parsing the document, all canvas are of type `Node` instead of `Canvas` (for pages in documents). It's then impossible to access to their children.

![image](https://user-images.githubusercontent.com/7687231/94011178-48256f00-fda7-11ea-828f-ccdc1b5bc2a1.png)

I guess that must be a parsing error.

**Comment by aloisdeniel** [comment]
My first attemp at solving it is available [here](https://github.com/aloisdeniel/figma/commit/f5e13408975173acb350de1326911e58ec2a129d);

**Comment by arnemolland** [comment]
Thanks @aloisdeniel! The changes look good to me, you're welcome to open a PR if you want.

**Comment by aloisdeniel** [comment]
Created one : #6 ! :)
