### ISSUE TITLE
Error 400: Bad Request

### ISSUE THREAD

**Issue by ivan-015** [dnb-asa/figma#5]
Hello! I am currently trying to use the Figma API endpoint with dart. 
I have tried using the `http` package as follows: 
`await http.get("https://api.figma.com/v1/files/2wRuvMlEmTeAjyCvET9DtB", headers: {
        'X-Figma-Token': '64232-6cc246bc-05ce-44fc-88c4-5e221a87ab1a',
  });
`
I have also tried to use the Dio package as follows:
`
Response tempResponse = await dio.get(
    'https://api.figma.com/v1/files/2wRuvMlEmTeAjyCvET9DtB',
    options: Options(
    headers: {
        'X-Figma-Token': '64232-6cc246bc-05ce-44fc-88c4-5e221a87ab1a',
    },
    ),
);
`
Finally, I tried to use the Figma dart package as follows:
`
final client = FigmaClient('64232-6cc246bc-05ce-44fc-88c4-5e221a87ab1a');
      await client.getFile('2wRuvMlEmTeAjyCvET9DtB').then((value) {
        print(value);
});
`

In all three cases, I get a 400, bad request error.

The weird thing is that when trying to do a curl request through the terminal it works fine. Is this an issue specifically with dart? 
Thank you for the help.

**Comment by aloisdeniel** [comment]
I'm currently facing the exact issue ...

**Comment by arnemolland** [comment]
Thanks for the report @ivan-015 and for the investigation @aloisdeniel 🕵️‍♂️

I'll migrate this package to http2 asap!

**Comment by aloisdeniel** [comment]
I'll propose a pull request. :)
